#!/usr/bin/env python3

from pathlib import Path
import random
import requests
import shlex
from subprocess import run, PIPE
import string
from tempfile import NamedTemporaryFile
import os

SQL_ENTRY='mysql -h {host} -u root -p\'{root_pw}\' -e "FLUSH PRIVILEGES; ALTER USER {user}@\'%\' IDENTIFIED BY \'{passwd}\'; FLUSH PRIVILEGES"'



def gen_passwd(num_chars=20, num_digits=4, num_punctuations=4):

    num_chars -= (num_digits + num_punctuations)
    punctuations = '!@$^&*()_+-;:|,.%'
    characters = [''.join([random.choice(string.ascii_letters) for i in range(num_chars)]),
                  ''.join([random.choice(string.digits) for i in range(num_digits)]),
                  ''.join([random.choice(punctuations) for i in range(num_punctuations)])]
    characters = ''.join(characters)
    return ''.join(random.sample(characters, len(characters)))

def set_passwd_in_sql_server(passwd):

    root_pw = os.environ['ROOT_PW']
    url = f'http://{os.environ["PROJECT"]}_vault:5002/vault/{passwd}/{root_pw}'
    print(url)
    cmd = SQL_ENTRY.format(user=os.environ["DB_USER"],
                           passwd=passwd,
                           host=f'{os.environ["PROJECT"]}_db',
                           root_pw=root_pw)
    res = requests.post(url).json()
    run(shlex.split(cmd))
    print(res)
    return

if __name__ == "__main__":
    password = gen_passwd()
    set_passwd_in_sql_server(password)

