stages:
    - doc

lint:
    stage: doc
    tags:
        - conda
    before_script:
        - python3 -m pip install .[test]
    script:
        - mypy --install-types --non-interactive
        - black --check src

pages:
    stage: doc
    tags:
        - conda
    script:
        - cd docs && make html
    before_script:
        - python3 -m pip install .[docs]
        - apt -y update
        - apt -y install make
    after_script:
        - mv docs/_build/html public
    artifacts:
        when: always
        paths:
            - public
