stages:
    - doc
pages:
  stage: doc
  tags:
    - sphinx
  script:
    - cd docs && make html
  before_script:
    - python3 -m pip install .[docs]
  after_script:
    - mv docs/_build/html public
  artifacts:
    when: always
    paths:
      - public
