stages:
    - doc
    - release

lint:
    image: python
    stage: doc
    needs: []
    tags:
        - docker, specific
    before_script:
        - python3 -m pip install .[test]
        - mkdir .mypy_cache
    script:
       # - mypy --install-types --non-interactive
        - black --check -t py310 src

pages:
    image: python
    stage: doc
    needs: []
    tags:
        - docker, specific
    script:
        - cd docs && make html
    before_script:
        - python3 -m pip install .[docs]
    after_script:
        - mv docs/_build/html public
    artifacts:
        when: always
        paths:
            - public

release_job:
    stage: release
    image: python
    needs: []
    tags:
        - docker, specific
    rules:
        - if: $CI_COMMIT_TAG
    before_script:
        - curl --location --output /usr/local/bin/release-cli
          "https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-linux-amd64"
        - pip install twine
        - chmod +x /usr/local/bin/release-cli
    script:
        - python setup.py sdist bdist_wheel
        - TWINE_PASSWORD=${PIPY_TOKEN}
          TWINE_USERNAME=__token__
          python -m twine upload --skip-existing --verbose dist/*
    release:
        tag_name: '$CI_COMMIT_TAG'
        description: '$CI_COMMIT_TAG'
