stages:
    - doc

lint:
    image: python
    stage: doc
    needs: []
    tags:
        - docker, specific
    before_script:
        - python3 -m pip install .[test]
    script:
        - mypy --install-types --non-interactive
        - black --check src

pages:
    image: python
    stage: doc
    needs: []
    tags:
        - docker, specific
    script:
        - cd docs && make html
    before_script:
        - python3 -m pip install .[docs]
    after_script:
        - mv docs/_build/html public
    artifacts:
        when: always
        paths:
            - public

release:
    image: python:latest

    run:
        script:
            - pip install twine
            - python setup.py sdist bdist_wheel
            - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
