#!/bin/sh
# Backup rotation


if ([ ! -d $1 ] && [ -z  "$2" ]);then
    echo Error: Usage $0 source_dir backup_dir
fi
mkdir -p $2
source_dir=$(readlink -f $1)
backup_dir=$(readlink -f $2)
let ndays=20
today=`date +%Y%m%dT%H%M`
let today_s=`date +%s`
let thresh=$(echo $ndays $today_s|awk '{print $2 - ($1 * 60 * 60 * 24)}')
let latest=0
for i in $(ls $backup_dir);do
    let created=$(date -d $(stat $backup_dir/$i|grep -i birth|awk '{print $2}'|sed "s/-/\//g") +%s)
    if [ $created -lt $thresh ];then
        rm -fr $i
    fi
    if [ $created -gt $latest ];then
        last_day=$i
    fi
done
if [ -z "$last_day" ];then
    rsync -av $source_dir/ $backup_dir/$today

else
    cp -al $backup_dir/$last_day $backup_dir/$today
    rsync -av --delete $source_dir/ $backup_dir/$today/
fi
