---
- name: Pulling container
  shell: |
    {{ deployment_method }} stop {{ web_name }} || true
    {{ deployment_method }} rm -f {{ web_name }} || true
    {{ deployment_method }} rmi -f  ghcr.io/freva-clint/freva-web:{{ web_version }}|| true
    {{ deployment_method }} pull ghcr.io/freva-clint/freva-web:{{ web_version }}
  changed_when: true

- name: Creating compose file
  template:
    src: "web-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{web_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ web_name }} compose --enable --project-name {{ web_name }}
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"
    DEBUG: '{{ debug }}'

- pause: seconds=301

- name: Container healthchecks
  script: >
    {{ docker_bin }} exec {{ web_name }} python -V
