---
- name: Pulling containers
  shell: |
    {{ deployment_method }} stop {{ web_name }} {{ web_cache_name }} {{web_proxy_name}}|| true
    {{ deployment_method }} rm -f {{ web_name }} {{ web_cache_name }} {{web_cache_name}}|| true
    {{ deployment_method }} rmi -f  ghcr.io/freva-clint/freva-web:{{ web_version }}|| true
    {{ deployment_method }} rmi -f  ghcr.io/freva-clint/freva-nginx|| true
    {{ deployment_method }} pull ghcr.io/freva-clint/freva-web:{{ web_version }}
    {{ deployment_method }} pull ghcr.io/freva-clint/freva-nginx:{{ proxy_version or "latest"}}
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose file
  template:
    src: "web-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{web_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ web_name }} compose --enable --project-name {{ project_name }}-web
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"
    DEBUG: '{{ debug }}'

- pause: seconds=30

- name: Run container health checks
  loop:
    - container: "{{ web_cache_name }}"
      command: "healthchecks -s redis"
      env: ""
    - container: "{{ web_proxy_name }}"
      command: "healthchecks -s nginx"
      env: ""
    - container: "{{ web_name }}"
      command: "/opt/conda/envs/freva-web/bin/python manage.py check"
      env: "-e GIT_PYTHON_REFRESH=quiet"
  script: >
    {{ docker_bin }} exec {{ item.env }} {{ item.container }} {{ item.command }}
  loop_control:
    label: "{{ item.container }}"
