---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Pulling containers
  shell: "{{ docker_bin }} {{ item }} || true"
  loop:
    - "stop {{ web_name }} {{ web_cache_name }} {{web_proxy_name}}"
    - "rm -f {{ web_name }} {{ web_cache_name }} {{web_cache_name}}"
    - "rmi -f  ghcr.io/freva-org/freva-web:{{ web_version }}"
    - "rmi -f  ghcr.io/freva-org/freva-nginx"
    - "pull ghcr.io/freva-org/freva-web:{{ web_version }}"
    - "pull ghcr.io/freva-org/freva-nginx:{{ proxy_version or 'latest'}}"
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose directory structure
  file:
    path: '{{ base_path }}/{{ project_name }}/compose_services'
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"


- name: Creating compose file
  template:
    src: "web-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{web_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ web_name }} compose --enable --project-name {{ project_name }}-web
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"

- pause: seconds=30

- name: Run container health checks
  loop:
    - container: "{{ web_cache_name }}"
      command: "healthchecks -s redis"
      env: ""
    - container: "{{ web_proxy_name }}"
      command: "healthchecks -s nginx"
      env: ""
    - container: "{{ web_name }}"
      command: "/opt/conda/envs/freva-web/bin/python manage.py check"
      env: "-e GIT_PYTHON_REFRESH=quiet"
  shell: >
    {{ docker_bin }} exec {{ item.env }} {{ item.container }} {{ item.command }}
  loop_control:
    label: "{{ item.container }}"
