---
- name: Include role vars
  include_vars: "{{ role_path }}/files/vars.yml"

- name: Set deployment task file
  set_fact:
    deployment_file: "{{ role_path }}/tasks/{{('container-deployment.yml' if deployment_method in ['docker', 'podman'] else 'conda-deployment.yml' if deployment_method == 'conda' else 'k8s-deployment.yml') | trim}}"
    play_file: "{{ role_path }}/tasks/{{('k8s-deployment.yml' if deployment_method == 'k8s' else 'systemd-based.yml') | trim}}"

- name: Playing {{ deployment_method }} deployment
  include_tasks: "{{ play_file | trim }}"
