version: '3'
services:
  {{solr_name}}:
    image: solr:latest
    container_name: {{solr_name}}
    hostname: {{solr_name}}
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{databrowser_name}}
{% endif %}
    environment:
      - CORE=files
      - NUM_BACKUPS=7
      - SOLR_HEAP={{databrowser_solr_mem}}
    volumes:
{% for volume in solr_volumes %}
      - {{volume}}
{% endfor %}
    tty: true
    ports:
      - 8983:8983

  {{mongo_name}}:
    image: mongo:latest
    container_name: {{mongo_name}}
    hostname: {{mongo_name}}
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{databrowser_name}}
{% endif %}
    environment:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD={{root_passwd}}
      - MONGO_INITDB_DATABASE=search_stats
    volumes:
{% for volume in mongo_volumes %}
      - {{volume}}
{% endfor %}
    ports:
      - 27017:27017
    tty: true

  {{databrowser_name}}:
    image: ghcr.io/freva-clint/databrowserapi:latest
    hostname: {{databrowser_name}}
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{databrowser_name}}
{% endif %}
    environment:
      - SOLR_CORE=files
{% if debug %}
      - SOLR_HOST=127.0.0.1:8983
      - MONGO_HOST=127.0.0.1:27017
{% else %}
      - SOLR_HOST={{solr_name}}:8983
      - MONGO_HOST={{mongo_name}}:27017
{% endif %}
      - MONGO_PASSWORD={{root_passwd}}
      - MONGO_DB=search_stats
      - MONGO_USER=mongo
    ports:
      - {{databrowser_port}}:8080
    container_name: {{databrowser_name}}
    depends_on:
      - {{solr_name}}
      - {{mongo_name}}
    tty: true

networks:
{% if debug is false %}
  hostnet:
    driver: host
{% else %}
  {{databrowser_name}}:
    driver: bridge
{% endif %}
