ansible_become: "{{ freva_rest_ansible_become_user is defined and freva_rest_ansible_become_user != '' }}"
ansible_python_interpreter: "{{ freva_rest_ansible_python_interpreter }}"
ansible_become_user: "{{ freva_rest_ansible_become_user | default('root') }}"
conda_path: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}/conda'
data_dir: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}'
systemd_unit_dir: "{{ '/etc/systemd/system' if  freva_rest_ansible_become_user is defined and freva_rest_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
compose_file: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/compose_services/{{freva_rest_name}}-compose.yml'
old_compose_dir: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/compose_services'
solr_name: "{{project_name}}-solr"
mongo_name: "{{project_name}}-mongo"
healthchecks:
  - name: "{{project_name}}-freva_rest"
    cmd:  'solr status'
  - name: "{{project_name}}-freva_rest"
    cmd: "python -c \"import pymongo; pymongo.MongoClient('mongodb://{{freva_rest_db_user}}:{{freva_rest_db_passwd}}@localhost:27017?timeoutMS=2000').list_database_names()\""
rest_volumes:
  - '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva_rest/data:/var/data:z'
  - '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva_rest/log:/var/log:z'
  - '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva-service-config/solr/daily_backup.sh:/usr/local/bin/daily_backup:z'
volume_dir: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}/freva_rest'
base_path: '{{freva_rest_data_path| regex_replace("^~", ansible_env.HOME)}}'
vault_name: "{{ project_name }}-vault"
vault_token_path: "{{ freva_rest_data_path|regex_replace('^~', ansible_env.HOME)}}/{{ project_name }}/vault_service/files/keys"
roles_path: "{{ asset_dir }}/playbooks/roles/freva-rest"
solr_data: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/solr_service'
databrowser_path: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/databrowser'
mongo_path: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva_rest/stats'
log_path: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva_rest/log'
cert_path: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/freva_rest/certs'
cron_job: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}/freva-service-config/solr/daily_backup.sh'
