version: '3'
services:
  {{vault_name}}:
    image: ghcr.io/freva-clint/freva-deployment/vault:{{vault_version}}
    hostname: {{vault_name}}
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    dns:
      - 8.8.8.8
      - 8.8.4.4
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{vault_name}}
{% endif %}
    environment:
      - ROOT_PW={{ root_passwd }}
    volumes:
{% for volume in vault_volumes %}
      - {{volume | expanduser}}
{% endfor %}
    container_name: {{vault_name}}
    tty: true
    ports:
      - 5002:5002

networks:
{%if debug %}
  hostnet:
    driver: host
{% else %}
  {{vault_name}}:
    driver: bridge
{% endif %}
