version: '3'
services:
  {{apache_name}}:
    image: httpd:latest
    container_name: {{apache_name}}
    hostname: {{apache_name}}
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{web_name}}
{% endif %}
    environment:
      - SCHEDULDER_DIR={{core_scheduler_output_dir}}
      - UID={{uid}}
      - GID={{gid}}
{% if debug %}
      - DATABROWSER_HOST=127.0.0.1
      - FREVA_HOST=127.0.0.1
      - HTTPD_PORT=9080
      - HTTPDS_PORT=9443
{% else %}
      - HTTPD_PORT=80
      - HTTPDS_PORT=443
      - DATABROWSER_HOST={{web_databrowser_host}}
      - FREVA_HOST={{web_server_name}}
{% endif %}
    volumes:
{% for volume in apache_volumes %}
      - {{volume}}
{% endfor %}
    command: /usr/local/bin/prepare-httpd
    ports:
      - {{web_port_httpd}}:80
      - {{web_port_httpsd}}:443
  {{redis_name}}:
    image: redis
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{web_name}}
{% endif %}
    ports:
      - 6379:6379
    tty: true
    container_name: {{redis_name}}
    hostname: {{redis_name}}

  {{web_name}}:
    image: ghcr.io/freva-clint/freva-web
    container_name: {{web_name}}
    hostname: {{web_name}}
{% if debug %}
    network_mode: host
{% else %}
    networks:
      - {{web_name}}
{% endif %}
    environment:
      - EVALUATION_SYSTEM_CONFIG_FILE={{core_root_dir}}/freva/evaluation_system.conf
      - LDAP_USER_DN={{web_ldap_user_dn}}
      - LDAP_USER_PW={{web_ldap_user_pw}}
      - DJANGO_SUPERUSER_PASSWORD={{ root_passwd }}
    volumes:
{% for volume in web_volumes %}
      - {{volume}}
{% endfor %}
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - {{redis_name}}
      - {{apache_name}}

networks:
{% if debug %}
  hostnet:
    driver: host
{% else %}
  {{web_name}}:
    driver: bridge
{% endif %}
