---
ansible_python_interpreter: "{{ web_ansible_python_interpreter }}"
old_compose_dir: "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/compose_services"
systemd_unit_dir: "{{ '/etc/systemd/system' if  web_ansible_become_user is defined and web_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
compose_file: "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/compose_services/{{web_name}}-compose.yml"
web_config_file: "{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}/freva/web/freva_web_conf.toml"
web_volumes:
  - "{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}:{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}:ro"
  - "{{ core_scheduler_output_dir|regex_replace('^~', ansible_env.HOME)}}:{{ core_scheduler_output_dir | regex_replace('^~', ansible_env.HOME)}}:ro"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/static:/opt/freva_web/static:z"
  - "{{core_base_dir_location|regex_replace('^~', ansible_env.HOME)}}:{{core_base_dir_location|regex_replace('^~', ansible_env.HOME)}}:ro"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/migrations:/opt/freva_web/base/migrations:z"
nginx_volumes:
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/freva_web.conf:/etc/nginx/nginx.conf:z"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/server-cert.crt:/tmp/server-cert.crt:z"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/server-key.key:/tmp/server-key.key:z"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/static:/srv/static:z"
  - "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/log:/var/log/web:z"
  - "{{ core_preview_path | regex_replace('^~', ansible_env.HOME)}}:/srv/static/preview:ro"
conda_path: '{{web_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}/conda'
data_dir: '{{web_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}'
redis_name: "{{ project_name }}-cache"
nginx_name: "{{project_name}}-httpd"
web_name: "{{project_name}}-web"
volume_dir: "{{web_data_path|regex_replace('^~', ansible_env.HOME)}}/{{project_name}}/web_service/"
ansible_become_user: "{{ web_ansible_become_user if web_ansible_become_user is defined else 'root' }}"
web_port_httpd: "{{ '80' if web_ansible_become_user == 'root' or ansible_user == 'root' else '9080' }}"
web_port_httpsd: "{{ '443' if web_ansible_become_user == 'root' or ansible_user == 'root'  else '9443' }}"
healthchecks:
  - name: "{{project_name}}-web"
    cmd:  'python -V'
  - name: "{{project_name}}-cache"
    cmd: 'redis-cli ping'
  - name: "{{project_name}}-httpd"
    cmd: 'nginx -t'
roles_path: "{{ asset_dir }}/playbooks/roles/web"
