---
- name: Creating web config on the core directory
  hosts: core
  become: "{{ core_ansible_become_user is defined and core_ansible_become_user != '' }}"
  vars:
    become: "{{ core_ansible_become_user is defined and core_ansible_become_user != '' }}"
    ansible_python_interpreter: "{{ core_ansible_python_interpreter }}"
    ansible_become_user: "{{ core_ansible_become_user if core_ansible_become_user is defined else 'root' }}"
  tasks:
    - name: Creating share directory
      file:
        path: "{{core_root_dir|regex_replace('^~', ansible_env.HOME)}}/freva/web"
        state: directory
        mode: "{{ '2775' if core_admin_group is defined and core_admin_group != '' else '2755' }}"
        group: "{{ core_admin_group if core_admin_group is defined and core_admin_group != '' else omit }}"

    - name: Adding freva web config to the core structure
      copy:
        src: "{{ core_config_toml_file | regex_replace('^~', ansible_env.HOME)}}"
        dest: "{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}/freva/web/freva_web_conf.toml"
        mode: "{{ '2664' if core_admin_group is defined and core_admin_group != '' else '2644' }}"
        group: "{{ core_admin_group if core_admin_group is defined and core_admin_group != '' else omit}}"

- name: Deploying web service
  hosts: web

  become: "{{ web_ansible_become_user is defined and web_ansible_become_user != '' }}"
  vars:
    ansible_python_interpreter: "{{ web_ansible_python_interpreter }}"
    become: "{{ web_ansible_become_user is defined and web_ansible_become_user != '' }}"
    web_config_file: "{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}/freva/web/freva_web_conf.toml"
    web_name: "{{project_name}}-web"
    conda_path: '{{web_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}'
    systemd_unit_dir: "{{ '/etc/systemd/system' if  web_ansible_become_user is defined and web_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
    ansible_become_user: "{{ web_ansible_become_user if web_ansible_become_user is defined else 'root' }}"
    web_port_httpd: "{{ '80' if web_ansible_become_user == 'root' or ansible_user == 'root' else '9080' }}"
    web_port_httpsd: "{{ '443' if web_ansible_become_user == 'root' or ansible_user == 'root'  else '9443' }}"

  tasks:

    - name: Getting register to core dir
      stat:
        path: "{{ core_root_dir | regex_replace('^~', ansible_env.HOME)}}/freva/evaluation_system.conf"
      register: core

    - name: Exiting if core path does not exist on machine
      fail:
        msg: >
          "Error: core not available on machine. "
          "The core hasn't been deployed yet, or wasn't mounted into its "
          "expected location: {{core_root_dir}}"
      when: core.stat.exists == false

    - name: Ensure the user systemd directory exists
      file:
        path: "{{ systemd_unit_dir }}"
        state: directory
        mode: "0755"

    - name: Get UID
      command: id -u {{ ansible_user }}
      register: uid_result

    - name: Get GID
      command: id -g {{ ansible_user }}
      register: gid_result

    - name: Set variables
      set_fact:
        uid: "{{ uid_result.stdout }}"
        gid: "{{ gid_result.stdout }}"
        log_dir: "{{conda_path}}/var/log/caching"

    - name: Register redis unit
      stat:
        path: "{{ systemd_unit_dir }}/{{project_name}}-cache.service"
      register: redis_unit

    - name: Run getent command
      command: "getent group {{gid}}"
      register: group_output
      changed_when: false
      failed_when: group_output.rc != 0 and group_output.stdout == ""

    - name: Extract group name
      set_fact:
        group_name: "{{ group_output.stdout.split(':')[0] }}"

    - name: Decode Base64 information content
      set_fact:
        information: "{{ web_cache_information | b64decode }}"

    - name: Set variables
      set_fact:
        redis_cert_dir: '{{conda_path}}/share/freva-rest-server/certs'
        username: "{{ information.user }}"
        password: "{{ information.passwd }}"

    - name: Creating redis data dir
      file:
        path: "{{redis_cert_dir}}"
        state: directory
        mode: "0755"
        recurse: true

    - name: Register redis cert file
      stat:
        path: "{{redis_cert_dir}}/client-key.pem"
      register: redis_cert

    - name: Write ssl key to file
      copy:
        content: "{{ information.ssl_key }}"
        dest: "{{redis_cert_dir}}/client-key.pem"
      when: (information.ssl_key | length > 0) and not redis_cert.stat.exists

    - name: Write ssl cert to file
      copy:
        content: "{{ information.ssl_cert }}"
        dest: "{{redis_cert_dir}}/client-cert.pem"
      when: (information.ssl_cert | length > 0) and not redis_cert.stat.exists

    - name: Creating log dir
      file:
        path: "{{log_dir}}"
        recurse: true

    - name: Creating redis unit
      template:
        src: "{{ asset_dir }}/freva-rest/redis.j2"
        dest: "{{ systemd_unit_dir }}/{{ project_name }}-cache.service"
        mode: "0644"
      when: not redis_unit.stat.exists

    - name: Applying redis settings
      set_fact:
        redis_settings:
          - "REDIS_USER={{username}}"
          - "REDIS_PASSWD={{password}}"
          - "REDIS_SSL_CERTFILE={{redis_cert_dir}}/client-cert.pem"
          - "REDIS_SSL_KEYFILE={{redis_cert_dir}}/client-key.pem"
      when: (information.ssl_cert | length > 0) or redis_cert.stat.exists

    - name: Applying redis settings
      set_fact:
        redis_settings:
          - "REDIS_USER={{username}}"
          - "REDIS_PASSWD={{password}}"
      when: (information.ssl_cert | length == 0) or not redis_cert.stat.exists

    - name: Creating temp. dir
      tempfile:
        state: directory
        prefix: evaluation_system
      register: tempdir

    - name: Registering conda path
      stat:
        path: "{{ conda_path }}"
      register: conda_env_path

    - name: Registering nginx path
      stat:
        path: "{{ conda_path }}/bin/nginx"
      register: http_bin

    - name: Downloading miniforge
      ansible.builtin.script:
        cmd: "{{ asset_dir }}/scripts/download_conda.py {{ tempdir.path }}"
      when: not conda_env_path.stat.exists

    - name: Creating conda dir
      file:
        path: "{{ conda_path }}"
        recurse: true
      when: not conda_env_path.stat.exists

    - name: Setting up conda environment
      shell:
        cmd: "./conda.sh -b -u -f -p {{conda_path}}"
        chdir: "{{ tempdir.path }}"
      when: not conda_env_path.stat.exists

    - name: Installing nginx
      shell:
        cmd: "{{conda_path}}/bin/mamba install -y redis-server nginx webpack-cli"
      when: not http_bin.stat.exists

    - name: Stopping the web service
      systemd:
        name: "{{ project_name }}-web"
        state: stopped
      ignore_errors: true

    - name: Registering web data path
      stat:
        path: "{{conda_path}}/share/freva-web"
      register: data_path

    - name: Deleting existing web-directory
      file:
        path: "{{conda_path}}/share/freva-web"
        state: absent
      when: data_path.stat.exists == true

    - name: Getting web app
      git:
        repo: https://github.com/FREVA-CLINT/freva-web.git
        dest: "{{conda_path}}/share/freva-web/app"
        version: main
        force: true

    - name: Creating aditional folders
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
        mode: "0775"
      with_items:
        - "{{conda_path}}/share/freva-web/app/static"
        - "{{conda_path}}/share/freva-web/certs"
        - "{{conda_path}}/share/freva-web/conf"
        - "{{conda_path}}/var/run/nginx"

    - name: Creating log dir
      file:
        path: "{{conda_path}}/var/log/nginx"
        recurse: true

    - name: Creating nginx config file.
      template:
        src: "{{ asset_dir }}/web/nginx.j2"
        dest: "{{ conda_path}}/share/freva-web/conf/freva_web.conf"
        mode: "0644"

    - name: Downloading mime-types file
      ansible.builtin.script:
        cmd: >
          {{ asset_dir }}/scripts/download.py
          https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types
          -o {{ conda_path }}/share/freva-web/conf/mime.types

    - name: Copying cert files
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        mode: "0775"
      with_items:
        - {src: "{{web_public_keyfile|regex_replace('^~', ansible_env.HOME)}}",
           dest: "{{conda_path}}/share/freva-web/certs/server-cert.crt"}
        - {src: "{{web_private_keyfile|regex_replace('^~', ansible_env.HOME)}}",
           dest: "{{conda_path}}/share/freva-web/certs/server-key.key"}

    - name: Installing conda dependencies
      shell:
        cmd: >
          {{conda_path}}/bin/mamba env update -n base -y
          --file {{conda_path}}/share/freva-web/app/conda-env.yml
      environment:
        MAMBA_ROOT_PREFIX: "{{conda_path}}"

    - name: Building js-code
      shell:
        cmd: "{{item}}"
        chdir: "{{conda_path}}/share/freva-web/app"
      with_items:
        - "npm install"
        - "npm run build-production"
      environment:
        PATH: "{{conda_path}}/bin:/usr/bin:/bin:/usr/local/bin"

    - name: Cleaning up
      file:
        path: "{{conda_path}}/share/freva-web/app/node_modules"
        state: absent

    - name: Adjusting permissions
      file:
        owner: "{{uid}}"
        group: "{{uid}}"
        recurse: true
        path: "{{item}}"
      with_items:
        - "{{conda_path}}/share/freva-web/app/static"
        - "{{conda_path}}/var/log/web"

    - name: Creating systemd unit service
      template:
        src: "{{ asset_dir }}/web/systemd.j2"
        dest: "{{ systemd_unit_dir }}/{{ project_name }}-web.service"
        mode: "0644"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true
        scope: "{{ 'system' if become is true else 'user'}}"

    - name: Enable and start the web server
      systemd:
        name: "{{ project_name }}-web"
        state: started
        enabled: true
        scope: "{{ 'system' if become is true else 'user'}}"

    - name: Display message about Apache HTTPD ports
      debug:
        msg: >
          Apache HTTPD is deployed on port {{ web_port_httpd }} instead of 80
          and {{ web_port_httpsd }} instead of 443.
          Since you are not running as root, consider setting up a reverse proxy
          to forward connections from port 80 and 443 to ports {{ web_port_httpd }}
          and {{ web_port_httpsd }} respectively.
      when: ansible_become_user != 'root'
