---
- name: Running common conda tasks
  include_tasks: "conda.yml"

- name: Creating environment file
  template:
    src: "service.env.j2"
    dest: "{{ data_dir }}/config/service.env"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  vars:
    service_name: "{{ db_name }}"
    env_vars:
      MYSQL_ROOT_PASSWORD: "{{ root_passwd }}"
      MYSQL_PASSWORD: "{{ db_passwd }}"
      MYSQL_DATABASE: "{{ db }}"
      MYSQL_USER: "{{ db_user }}"
      PROJECT: "{{ project_name }}"
      HOST: "{{ db_host }}"
      CONDA_PREFIX: "{{ conda_path }}"
      API_DATA_DIR: "{{ data_dir }}/data"
      API_LOG_DIR: "{{ data_dir }}/logs"
      API_CONFIG_DIR: "{{ conda_path }}/share/freva-rest-server/mysql"

- name: Creating mysql systemd service
  template:
    src: "systemd-mysql-conda.j2"
    dest: "{{ systemd_unit_dir }}/{{ db_name }}.service"
    mode: "0644"

- name: Enable and start the freva mysql server
  systemd:
    name: "{{ db_name }}"
    state: started
    enabled: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- pause: seconds=15

- name: DB health check
  shell: >
    {{ conda_path }}/bin/mysql -u root -p${MYSQL_ROOT_PASSWORD}
    -e "SHOW GLOBAL STATUS LIKE 'Threads_connected';"
  environment:
    MYSQL_ROOT_PASSWORD: "{{ root_passwd }}"

- name: Download daily mysql backup script
  get_url:
    url: https://raw.githubusercontent.com/FREVA-CLINT/freva-service-config/refs/heads/main/mysql/daily_backup.sh
    dest: "{{ data_dir }}/bin/mysql-daily-backup.sh"
    mode: '0755'
