---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Pulling container
  shell: "{{ docker_bin }} {{ item }} || true"
  loop:
    - "stop {{ db_name }}"
    - "rm -f {{ db_name }}"
    - "rmi -f ghcr.io/freva-clint/freva-mysql"
    - "pull ghcr.io/freva-clint/freva-mysql:{{db_version}}"
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Checking mysql update info
  shell: >
    {{ docker_bin }} run --rm
    -v {{ db_name}}_data:/data:ro
    alpine sh -c "cat /data/mysql_upgrade_info 2> /dev/null ||
    cat /data/mariadb_upgrade_info 2> /dev/null
    || echo mysql"
  register:
    upgrade_info_cmd
  changed_when: false

- name: "Setting the upgrade_info as fact"
  set_fact:
    upgrade_info_text: "{{ upgrade_info_cmd.stdout | lower }}"

- name: Migrate Old MariaDB to MySQL
  when: "'mariadb' in upgrade_info_text"
  block:
    - name: Backup MariaDB data directory before migration
      shell: >
        {{ docker_bin }} run --rm -v {{db_name}}_data:/data:ro
        -v mysql_backup:/backup:rw --name backup-db
        alpine sh -c "tar czf /backup/mysql-backup.tar.gz -C /data ."
      changed_when: true

    - name: Perform migration using included playbook
      include_tasks:
        file: "mariadb_to_mysql_migration.yml"

  rescue:

    - name: Restore original MariaDB data directory
      shell: >
        {{ docker_bin }} run --rm
        -v {{db_name}}_data:/data:z --name restore-db
        -v mysql_backup:/backup:ro
        alpine sh -c "rm -rf /data/* && tar xzf /backup/mysql-backup.tar.gz -C /data"
      changed_when: true

    - name: Fail hard and notify user
      fail:
        msg: >
          MariaDB-to-MySQL migration failed. Original MariaDB data was
          restored. Aborting deployment.

  always:

    - name: Stop temp container if running
      shell: >
        {{ compose_bin }} -f {{ db_tempdir.path }}/temp-container.yaml
        down --remove-orphans
      ignore_errors: true

    - name: Remove any existing DB backup
      shell: >
        {{ docker_bin }} volume rm -f mysql_backup


- name: Creating compose directory structure
  file:
    path: '{{ base_path }}/{{ project_name }}/compose_services'
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: Creating compose file
  template:
    src: "db-server-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating system services
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ db_name }} compose --enable --project-name {{db_name}}
    -f {{compose_file}} up --remove-orphans
  environment:
    PREFER: "{{deployment_method }}"

- pause: seconds=15

- name: health check
  shell: >
    {{ docker_bin }} exec {{ db_name }}
    sh -c 'healthchecks -s mysql'
