---
- name: Cleaning existing directory structure
  file:
    path: '{{ data_dir }}'
    state: absent
  when: wipe is true

- name: Creating service directory structure
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    recurse: true
  loop:
    - "{{ data_dir }}"
    - "{{ data_dir }}/data"
    - "{{ data_dir }}/backups"
    - "{{ data_dir }}/logs"
    - "{{ data_dir }}/config"
    - "{{ data_dir }}/bin"

- name: Registering conda path
  stat:
    path: "{{ conda_path }}"
  register: conda_env_path

- name: Setting conda command fact
  set_fact:
    conda_cmd: "install"

- name: Overriding conda command fact
  set_fact:
    conda_cmd: "create"
  when: not conda_env_path.stat.exists

- name: Downloading micromamba
  script:
    cmd: "{{ asset_dir }}/scripts/download_conda.py {{ data_dir }}"

- name: Installing mamba packages {{conda_packages | join(' ')}}
  shell:
    cmd: >
      {{ data_dir }}/bin/micromamba {{ conda_cmd }} -p {{conda_path }}
      -c conda-forge --override-channels
      -y git curl {{ conda_packages | join(' ')}}
  environment:
    MAMBA_ROOT_PREFIX: "{{ conda_path }}"

- name: Getting service startup scripts
  shell: >
    {{ data_dir }}/bin/micromamba run -p {{ conda_path }} curl
    https://raw.githubusercontent.com/FREVA-CLINT/freva-service-config/refs/heads/main/conda-services/create.sh
    | bash
  environment:
    CONDA_PREFIX: "{{ conda_path }}"
    PATH: "{{ conda_path }}/bin:{{ ansible_env.PATH }}"

- name: Getting binaries
  include_tasks: "paths.yml"
