---
- name: Create and prepare volumes
  block:
    - name: Cleaning volumes
      shell: >
        {{ deployment_method }} volume rm -f {{ item }}
      loop: "{{ volume_names  | default([]) }}"
      when: wipe | default(false)

    - name: Create volumes
      shell: >
        {{ deployment_method }} volume create {{ item }} --ignore
      loop: "{{ volume_names  | default([]) }}"

    - name: Adjust ownership of volume directories
      shell: >
        {{ deployment_method }} run --rm -v {{ item }}:/data:rw alpine
        chown -R {{uid}}:{{gid}} /data
      loop: "{{ volume_names  | default([]) }}"
