ansible_python_interpreter: "{{ core_ansible_python_interpreter }}"
ansible_become_user: "{{ core_ansible_become_user if core_ansible_become_user is defined else 'root' }}"
web_path: "{{core_root_dir|regex_replace('^~', ansible_env.HOME)}}/freva/web"
