#!/bin/sh
# Simple warpper to call docker or podman depending on what is available

container_cmd=$(which podman 2> /dev/null || which docker 2> /dev/null)
if [ -z "$container_cmd" ];then
    echo Docker or Podman must be installed on the system
    exit 1
fi
${container_cmd} $@
