---
- name: Build vault
  block:
    - name: Creating temporary vault build dir
      tempfile:
        prefix: vault-build.
        state: directory
      register: vault_tempdir

    - name: Get latest Vault release metadata from GitHub
      uri:
        url: https://api.github.com/repos/hashicorp/vault/releases/latest
        return_content: yes
      register: vault_release_data

    - name: Extract latest version tag from JSON
      set_fact:
        vault_latest_version: "{{ vault_release_data.json.tag_name }}"

    - name: Set Vault download variables
      ansible.builtin.set_fact:
        vault_tarball_url: "https://github.com/hashicorp/vault/archive/refs/tags/{{ vault_latest_version }}.tar.gz"
        vault_bin_path: "{{ conda_path }}/bin/vault"

    - name: Extract Vault source
      unarchive:
        src: "{{ vault_tarball_url }}"
        dest: "{{ vault_tempdir.path }}"
        remote_src: true
        extra_opts:
          - --strip-components=1

    - name: Build Vault binary
      command:
        cmd: >
          go build
          -buildmode=pie
          -trimpath
          -modcacherw
          -o={{ vault_bin_path }}
          -ldflags="-s -w"
      args:
        chdir: "{{ vault_tempdir.path }}"
      environment:
        CGO_ENABLED: "0"
        GO111MODULE: "on"
        PATH: "{{ conda_path }}/bin:{{ ansible_env.PATH }}"

  always:
    - name: Delete temporary vault build dir
      file:
        path: "{{ vault_tempdir.path}}"
        state: absent
