---
- name: Register path to vault keys
  stat:
    path: "{{ vault_token_path }}"
  register: token_path

- name: Check vault keys
  block:
    - name: Base64 decode vault key path
      command: base64 -d "{{vault_token_path}}"
  rescue:
    - name: Delete vault dir because its content is not valid
      file:
        state: absent
        path: "{{ data_dir }}"
  when: token_path.stat.exists

- name: Running common conda tasks
  include_tasks: "conda.yml"

- name: Build vault service
  include_tasks: "{{ role_path }}/tasks/build-vault.yml"

- name: Creating environment file
  template:
    src: "service.env.j2"
    dest: "{{ data_dir }}/config/service.env"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  vars:
    service_name: "{{ vault_name }}"
    env_vars:
      KEY_FILE: "{{ data_dir }}/data/keys"
      ROOT_PW: "{{ root_passwd }}"
      VERSION: "{{ vault_version }}"
      CONDA_PREFIX:  "{{ conda_path }}"

- name: Enable and start the freva vault server
  systemd:
    name: "{{ project_name }}-vault"
    state: started
    enabled: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- pause: seconds=15

- name: Add DB secrets to vault
  shell: >
    {{ conda_path }}/bin/add-vault-secret
    data -s db.container {{ vault_name }} -s db.host {{ vault_db_host }}
    -s db.port {{ vault_db_port }} -s db.db {{ vault_db }}
    -s db.passwd '{{ debug | ternary(root_passwd, vault_passwd) }}'
    -s db.user {{ debug | ternary('root', vault_db_user) }}
  environment:
    ROOT_PW: "{{ root_passwd }}"
    PATH: "{{ conda_path }}/bin:/usr/bin:/bin:/usr/local/bin"
