---
- name: Running common taks
  include_tasks: "common_tasks.yml"

- name: Stopping the {{vault_name }} service
  systemd:
    name: "{{ vault_name }}"
    state: stopped
    enabled: false
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
  ignore_errors: true
  failed_when: false

- name: Removing old {{vault_name}} services file
  file:
    state: absent
    force: true
    path: "{{ systemd_unit_dir }}/{{ vault_name }}.service"

- name: Playing the {{ deployment_method }} tasks
  include_tasks:
    file: "{{ deployment_file | trim }}"
