---
- name: Pulling container
  shell: |
    {{ deployment_method }} stop {{ freva_rest_name }} || true
    {{ deployment_method }} rm -f {{ freva_rest_name }} || true
    {{ deployment_method }} rmi -f ghcr.io/freva-clint/freva-rest-api:{{ freva_rest_version }}|| true
    {{ deployment_method }} pull ghcr.io/freva-clint/freva-rest-api:{{ freva_rest_version }}
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose file
  template:
    src: "freva-rest-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{freva_rest_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ freva_rest_name }} compose --enable --project-name {{ freva_rest_name }}
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"
    DEBUG: '{{ debug }}'
