---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Pulling container
  shell: "{{ docker_bin }} {{ item }} || true"
  loop:
    - "stop {{ freva_rest_name }}"
    - "rm -f {{ freva_rest_name }}"
    - "rmi -f ghcr.io/freva-org/freva-rest-api:{{ freva_rest_version }}"
    - "pull ghcr.io/freva-org/freva-rest-api:{{ freva_rest_version }}"
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose directory structure
  file:
    path: '{{ base_path }}/{{ project_name }}/compose_services'
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"


- name: Creating compose file
  template:
    src: "freva-rest-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{freva_rest_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ freva_rest_name }} compose --enable --project-name {{ freva_rest_name }}
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"
