---
- name: Running common taks
  include_tasks: "common_tasks.yml"

- block:
    - name: Create tempfile for secrets
      tempfile:
        prefix: "secrets."
      register: secrets_file

    - name: Write secret to tempfile
      copy:
        src: "{{ cache_secrets }}"
        dest: "{{ secrets_file.path }}"

    - name: Slurp and decode secret on remote
      slurp:
         src: "{{ secrets_file.path }}"
      register: slurped

    - name: Set decoded + parsed secret as fact
      set_fact:
        cache_information: "{{ slurped.content | b64decode | b64decode | from_json}}"
        cache_information_enc: "{{ slurped.content | b64decode }}"

  always:

      - name: Remove temporary secret file from remote
        file:
          path: "{{ secrets_file.path }}"
          state: absent

- name: Stopping the {{ freva_rest_name }} service
  systemd:
    name: "{{ freva_rest_name }}"
    state: stopped
    enabled: false
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
  ignore_errors: true
  failed_when: false

- name: Removing old services files
  file:
    state: absent
    force: true
    path: "{{ systemd_unit_dir }}/{{ freva_rest_name }}.service"

- name: Playing the {{ deployment_method }} tasks
  include_tasks:
    file: "{{ deployment_file | trim }}"
