---
service: vault
ansible_become: "{{ vault_ansible_become_user is defined and vault_ansible_become_user != '' }}"
ansible_python_interpreter: "{{ vault_ansible_python_interpreter }}"
ansible_become_user: "{{ vault_ansible_become_user | default('root') }}"
admin_user: "{{ vault_admin_user | default('') }}"
base_path: '{{vault_data_path | regex_replace("^~", ansible_env.HOME)}}'
conda_path: '{{ base_path }}/{{ project_name }}/services/{{ service }}/conda'
data_dir: '{{ base_path }}/{{ project_name }}/services/{{service}}'
systemd_unit_dir: "{{ '/etc/systemd/system' if  vault_ansible_become_user is defined and vault_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
vault_name: "{{ project_name }}-vault"
compose_file: '{{ base_path }}/{{project_name}}/compose_services/{{vault_name}}-compose.yml'
old_compose_dir: '{{ base_path }}/compose_services'
vault_token_path: "{{ data_dir }}/data/files/keys"
wipe: "{{ vault_wipe }}"
volume_names:
  - "{{ vault_name }}_data"
conda_packages:
  - vault>=1.19
  - fastapi
  - pyopenssl
  - uvicorn
  - requests
  - hvac
