---
- hosts: core

  vars:
    - ansible_python_interpreter: "{{ core_ansible_python_interpreter }}"
    - ansible_become_user: >
        "{{ core_ansible_become_user
        if core_ansible_become_user is defined else 'root' }}"
    - allow_world_readable_tmpfiles: true
    - conda_exec_path: >
        "{{ core_conda_exec_path
        if core_conda_exec_path is defined else '' }}"
    - eval_path: "freva/evaluation_system.conf"
  tasks:
    - name: Cleaning up temporary files
      file:
        state: absent
        path: /tmp/evaluation_system
    - name: Cloning the evluation_system reposiotry
      git:
        repo: "{{ core_git_url }}"
        dest: /tmp/evaluation_system
        executable: "{{core_git_path}}"
      become: "{{'true' if core_ansible_become_user is defined else 'no' }}"
    - name: Preparing creation of directory structure
      file:
        path: "{{ core_root_dir }}"
        state: directory
    - name: Creating directory structure with admin group
      file:
        path: "{{ item }}"
        state: directory
        mode: "2775"
        group: "{{core_admin_group}}"
      with_items:
        - "{{ core_root_dir }}/freva/"
        - "{{ core_root_dir }}/plugins/"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
      when: core_admin_group is defined
    - name: Creating directory structure without admin group
      file:
        path: "{{ item }}"
        state: directory
        mode: "2775"
      with_items:
        - "{{ core_root_dir }}/freva/"
        - "{{ core_root_dir }}/plugins/"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
      when: core_admin_group is not defined
    - name: Creating user work directory
      file:
        path: "{{core_base_dir_location}}"
        state: directory
        mode: "3775"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
      when: core_base_dir_location | length != 0
      ignore_errors: true
    - name: Creating workload manager output
      file:
        path: "{{core_scheduler_output_dir}}"
        state: directory
        mode: "3775"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
      ignore_errors: true
      when: core_scheduler_output_dir | length != 0
    - name: Creating preview path
      file:
        path: "{{core_preview_path}}"
        state: directory
        mode: "3775"
      when: core_preview_path | length != 0
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
      ignore_errors: true
    - name: Inserting evaluation_sytem.conf file without admin group
      copy:
        src: "{{ core_dump }}"
        dest: "{{ core_root_dir }}/freva/evaluation_system.conf"
        mode: "1644"
    - name: Inserting evaluation_system.config file to temp location
      copy:
        src: "{{ core_dump }}"
        dest: /tmp/evaluation_system/evaluation_system.conf
      become: "{{'true' if core_ansible_become_user is defined else 'no' }}"
    - name: Deploying evaluation_system
      shell:
        cmd: $PYTHON3 deploy.py {{ core_install_dir }} -s --arch {{core_arch}} --packages freva
        chdir: /tmp/evaluation_system
      environment:
        CONDA_EXEC_PATH: "{{ conda_exec_path }}"
        PYTHON3: "{{ ansible_python_interpreter }}"
        PYTHON_VERSION: ""
        EVALUATION_SYSTEM_CONFIG_FILE: "/tmp/evaluation_system/evaluation_system.conf"
      when: (core_install is true)
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
    - name: Inserting evaluation_sytem.conf file with admin group
      copy:
        src: "{{ core_dump }}"
        dest: "{{ core_root_dir }}/freva/evaluation_system.conf"
        mode: "1664"
        group: "{{core_admin_group}}"
      become: "{{'true' if core_ansible_become_user is defined else 'no' }}"
      when: core_admin_group is defined
    - name: Installing additional python packages
      shell:
        cmd: python -m pip install "{{item}}"
      environment:
        PATH: "{{core_install_dir}}/bin"
      with_items:
        - "git+https://gitlab.dkrz.de/k204230/install-kernelspec.git"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
    - name: Inserting drs_config.toml file
      copy:
        src: "/tmp/evaluation_system/assets/drs_config.toml"
        dest: "{{ core_root_dir }}/freva/drs_config.toml"
        remote_src: true
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
    - name: Configuring evaluation_system
      shell:
        cmd: $PYTHON3 deploy.py {{ core_install_dir }} -s --no-conda
        chdir: /tmp/evaluation_system
      environment:
        PYTHON3: "{{ ansible_python_interpreter }}"
        EVALUATION_SYSTEM_CONFIG_FILE: "{{ core_root_dir }}/freva/evaluation_system.conf"
        PYTHON_VERSION: ""
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
    - name: Copying Public key file
      copy:
        src: "{{ core_keyfile }}"
        dest: "{{ core_root_dir }}/freva/{{ project_name }}.crt"
        mode: "2644"
      become: "{{'yes' if core_ansible_become_user is defined else 'no' }}"
    - name: Deleting temporary files
      file:
        state: absent
        path: /tmp/evaluation_system
