---
- hosts: db

  vars:
    - ansible_python_interpreter: "{{ db_ansible_python_interpreter }}"
    - docker_cmd: >
        --net {{ project_name }} -v
        /opt/freva/{{project_name}}/db_service:/var/lib/mysql:z
        --name {{ db_name }} -e HOST={{ db_host }}
        -e NUM_BACKUPS=7
        -e PROJECT={{ project_name }}
        -e MYSQL_USER={{db_user}}
        -e MYSQL_PASSWORD='{{db_passwd}}'
        -e MYSQL_DATABASE={{db_db}}
        -e BACKUP_DIR=/var/lib/mysql/backup
        -p {{ db_port }}:3306
        -e MYSQL_ROOT_PASSWORD='{{ root_passwd }}'
        -v /root/freva-service-config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/002_create_tables.sql:z
        -v /root/freva-service-config/mysql/daily_backup.sh:/usr/local/bin/daily_backup:z
        -t mariadb:latest
    - skip_tables_cmd: >
        --net {{ project_name }} -v
        /opt/freva/{{project_name}}/db_service:/var/lib/mysql:z
        --name {{ db_name }} -e HOST={{ db_host }}
        -e NUM_BACKUPS=7
        -e PROJECT={{ project_name }}
        -e MYSQL_USER={{db_user}}
        -e MYSQL_PASSWORD='{{db_passwd}}'
        -e MYSQL_DATABASE={{db_db}}
        -e BACKUP_DIR=/var/lib/mysql/backup
        -p {{ db_port }}:3306
        -e MYSQL_ROOT_PASSWORD='{{ root_passwd }}'
        -v /root/freva-service-config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/002_create_tables.sql:z
        -v /root/freva-service-config/mysql/daily_backup.sh:/usr/local/bin/daily_backup:z
        -t mariadb:latest mysqld_safe --skip-grant-tables
    - continer_name: "{{ db_name }}"
    - vault_name: "{{project_name}}-vault"
  tasks:
    - name: Copying docker/podman wrapper script
      copy:
        src: "{{ asset_dir }}/scripts/docker-or-podman"
        dest: /usr/local/bin/docker-or-podman
        mode: "0775"
      become: true
    - name: Registering systemctl path
      stat:
        path: /usr/bin/systemctl
      register: systemctl
    - name: Registering anacron path
      stat:
        path: /etc/cron.daily
      register: cron
    - name: Stopping services and deleting existing containers
      shell: >
        /usr/local/bin/docker-or-podman stop {{db_name}};
        systemctl stop {{db_name}};
        /usr/local/bin/docker-or-podman rm {{db_name}};
        /usr/local/bin/docker-or-podman rmi -f mariadb;
        echo 0
      become: true
      ignore_errors: true
    - name: Deleting config file
      file:
        state: absent
        force: true
        path: "/root/freva-service-config/"
      become: true
    - name: Pulling container
      become: true
      shell: /usr/local/bin/docker-or-podman pull mariadb:latest
    - name: Creating docker network
      shell: >
        /usr/local/bin/docker-or-podman network create "{{ project_name }}";
        echo 0
      become: true
    - name: Cleaning existing directory structure
      file:
        path: /opt/freva/{{ project_name }}/db_service
        state: absent
      become: true
      when: wipe == true
    - name: Creating directory structure
      file:
        path: /opt/freva/{{ project_name }}/db_service
        state: directory
        recurse: true
        group: 999
        owner: 999
      become: true
    - name: Copying auxillary files to target machine
      become: true
      copy: src="{{ asset_dir }}/db_service/reset_root_pw.sh" dest=/tmp/
    - name: Copying systemd files
      copy:
        src: "{{ asset_dir }}/scripts/{{ item }}"
        dest: /tmp/{{ item }}
        mode: '0755'
      with_items:
        - "create_systemd.py"
        - "create_cron.sh"
    - name: Getting additional configurations
      become: true
      git:
        repo: https://github.com/FREVA-CLINT/freva-service-config.git
        dest: /root/freva-service-config
        update: true
    - name: Preparing the root password reset I
      become: true
      shell: /usr/local/bin/docker-or-podman run -d {{docker_cmd}}
    - pause: seconds=5
    - name: Preparing the root password reset II
      become: true
      shell: |
        /usr/local/bin/docker-or-podman stop {{db_name}}
        /usr/local/bin/docker-or-podman rm {{db_name}}
    - name: Preparing the root password reset III
      become: true
      shell: /usr/local/bin/docker-or-podman run -d {{skip_tables_cmd}}
    - pause: seconds=2
    - name: Preparing the root password reset IV
      become: true
      shell:  /usr/local/bin/docker-or-podman cp /tmp/reset_root_pw.sh {{db_name}}:/tmp
    - name: Resetting the root password
      become: true
      shell: /usr/local/bin/docker-or-podman exec -it {{db_name}} bash /tmp/reset_root_pw.sh
    - name: Deleting temp. container
      become: true
      shell: |
        /usr/local/bin/docker-or-podman stop {{db_name}}
        /usr/local/bin/docker-or-podman rm {{db_name}}
    - name: Creating the mysql docker container
      shell: /usr/local/bin/docker-or-podman run -d {{docker_cmd}}
      become: true
    - name: Creating systemd service
      become: true
      shell: >
        /tmp/create_systemd.py {{db_name}} --requires {{vault_name}} --enable
      when: systemctl.stat.exists == true
    - name: Creating cron jobs
      become: true
      shell: sh /tmp/create_cron.sh "{{ db_name }}" "{{db_email}}"
      when: cron.stat.exists == true
    - name: Deleting auxillary files
      become: true
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/create_systemd.py
        - /tmp/create_cron.sh
        - /tmp/reset_root_pw.sh
    - name: Restarting docker container
      become: true
      shell: systemctl restart "{{ db_name }}"
      when: systemctl.stat.exists == true
