---
- hosts: db

  vars:
    - ansible_python_interpreter: "{{ db_ansible_python_interpreter }}"
    - docker_cmd: >
        --net {{ project_name }} -v
        /opt/freva/{{project_name}}/db_service:/var/lib/mysql:z
        --name {{ db_name }} -e HOST={{ db_host }}
        -e NUM_BACKUPS=7
        -e PROJECT={{ project_name }}
        -e MYSQL_USER={{db_user}}
        -e MYSQL_PASSWORD='{{db_passwd}}'
        -e MYSQL_DATABASE={{db_db}}
        -p {{ db_port }}:3306
        -e MYSQL_ROOT_PASSWORD={{ root_passwd }}
        -v /root/freva-service-config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/002_create_tables.sql:z
        -v /root/freva-service-config/mysql/daily_backup.sh:/usr/local/bin/daily_backup:z
        -t mariadb:latest
    - continer_name: "{{ db_name }}"
    - vault_name: "{{project_name}}-vault"
  tasks:
    - name: Copying docker/podman wrapper script
      copy:
        src: "{{ asset_dir }}/scripts/docker-or-podman"
        dest: /usr/local/bin/docker-or-podman
        mode: "0775"
      become: true
    - name: Registering systemctl path
      stat:
        path: /usr/bin/systemctl
      register: systemctl
    - name: Stopping services and deleting existing containers
      shell: >
        /usr/local/bin/docker-or-podman stop {{db_name}};
        systemctl stop {{db_name}};
        /usr/local/bin/docker-or-podman rm {{db_name}};
        echo 0
      become: true
      ignore_errors: true
    - name: Creating docker network
      shell: >
        /usr/local/bin/docker-or-podman network create "{{ project_name }}";
        echo 0
      become: true
    - name: Cleaning existing directory structure
      file:
        path: /opt/freva/{{ project_name }}/db_service
        state: absent
      become: true
    - name: Creating directory structure
      file:
        path: /opt/freva/{{ project_name }}/db_service
        state: directory
        recurse: true
        group: 999
        owner: 999
      become: true
    - name: Copying auxillary files to target machine
      copy: src="{{ asset_dir }}/db_service" dest=/tmp
    - name: Copying cron create script to target machine
      copy: src="{{ asset_dir }}/scripts/create_cron.sh" dest=/tmp/db_service/
    - name: Copying systemd files
      copy:
        src: "{{ asset_dir }}/scripts/{{ item }}"
        dest: /tmp/{{ item }}
        mode: '0755'
      with_items:
        - "create_systemd.py"
    - name: Getting additional configurations
      become: true
      git:
        repo: https://gitlab.dkrz.de/freva/freva-service-config.git
        dest: /root/freva-service-config
        version: init
        update: true
    - name: Creating the mysql docker container
      shell: /usr/local/bin/docker-or-podman run -d {{docker_cmd}}
      become: true
    - name: Creating systemd service
      become: true
      shell: >
        /tmp/create_systemd.py {{db_name}} --requires {{vault_name}} --enable
      when: systemctl.stat.exists == true
    - name: Creating cron jobs
      become: true
      shell: sh /tmp/db_service/create_cron.sh "{{ db_name }}" "{{db_email}}"
    - name: Deleting auxillary files
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/create_systemd.py
        - /tmp/db_service
    - name: Restarting docker container
      become: true
      shell: systemctl restart "{{ db_name }}"
      when: systemctl.stat.exists == true
