version: '3'
services:

  {{apache_name}}:
    image: httpd:latest
    container_name: {{apache_name}}
    hostname: {{apache_name}}
    networks:
      - {{project_name}}
    environment:
      - SCHEDULER_DIR={{core_scheduler_output_dir}}
      - UID={{uid}}
      - GID={{gid}}
      - DATABROWSER_HOST={{web_databrowser_host}}
      - FREVA_HOST={{web_server_name}}
    volumes:
{% for volume in apache_volumes %}
      - {{volume}}
{% endfor %}
    command: /usr/local/bin/prepare-httpd
    ports:
      - 80:80
      - 443:443

  {{redis_name}}:
    image: redis
    networks:
      - {{project_name}}
    ports:
      - 6379:6379
    tty: true

  {{web_name}}:
    image: ghcr.io/freva-clint/freva-web
    container_name: {{web_name}}
    hostname: {{web_name}}
    networks:
      - {{project_name}}
    environment:
      - EVALUATION_SYSTEM_CONFIG_FILE={{core_root_dir}}/freva/evaluation_system.conf
      - LDAP_USER_DN={{web_ldap_user_dn}}
      - LDAP_USER_PW={{web_ldap_user_pw}}
      - DJANGO_SUPERUSER_PASSWORD={{ root_passwd }}
    volumes:
    container_name: {{redis_name}}
    hostname: {{redis_name}}
{% for volume in web_volumes %}
      - {{volume}}
{% endfor %}
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - {{redis_name}}
      - {{apache_name}}

networks:
  {{project_name}}:
    driver: bridge
