---
- name: Running common conda tasks
  include_tasks: "conda.yml"

- name: Creating environment file
  template:
    src: "service.env.j2"
    dest: "{{ data_dir }}/config/service.env"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  vars:
    service_name: "{{ mongo_name }}"
    env_vars:
      API_MONGO_PASSWORD: "{{mongodb_server_db_passwd}}"
      API_MONGO_DB: "search_stats"
      API_MONGO_USER: "{{mongodb_server_db_user}}"
      CONDA_PREFIX: "{{ conda_path }}"
      API_DATA_DIR: "{{ data_dir }}/data"
      API_LOG_DIR: "{{ data_dir }}/logs"
      API_CONFIG_DIR: "{{ data_dir }}/config"

- name: Creating systemd unit service
  template:
    src: "systemd-conda.j2"
    dest: "{{ systemd_unit_dir }}/{{ mongo_name }}.service"
    mode: "0644"

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- name: Enable and start the {{ mongo_name }} service
  systemd:
    name: "{{ mongo_name }}"
    state: started
    enabled: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- pause: seconds=15

- name: Performing healthchecks
  shell: >
    {{conda_path}}/libexec/freva-rest-server/healthchecks.sh
    -s mongo
  environment:
    PATH: "{{conda_path}}/bin:/usr/bin:/bin:/usr/local/bin"
    API_MONGO_PASSWORD: "{{mongodb_server_db_passwd}}"
    API_MONGO_DB: "search_stats"
    API_MONGO_USER: "{{mongodb_server_db_user}}"
