---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Pulling container
  shell: "{{ docker_bin }} {{ item }} || true"
  loop:
    - "stop {{ mongo_name }}"
    - "rm -f {{ mongo_name }}"
    - "rmi -f ghcr.io/freva-clint/freva-mongo"
    - "pull ghcr.io/freva-clint/freva-mongo:{{mongodb_server_version}}"
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose file
  template:
    src: "mongo-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{mongo_name}} service
  script: >
    {{asset_dir}}/scripts/create_systemd.py
    {{mongo_name}} compose --enable --project-name {{mongo_name}}
    -f {{compose_file}} up --remove-orphans
  environment:
    DEBUG: '{{ debug }}'
    PREFER: "{{deployment_method }}"

- pause: seconds=15

- name: Container healthchecks
  shell: >
    {{ docker_bin }} exec {{ mongo_name }} healthchecks -s mongo
