ansible_python_interpreter: "{{ core_ansible_python_interpreter }}"
conda_bin: "{{ core_install_dir | regex_replace('^~', ansible_env.HOME) }}/bin"
conda_sbin: "{{ core_install_dir | regex_replace('^~', ansible_env.HOME) }}/sbin"
pkg_mgr: "conda"
ansible_become_user: "{{ core_ansible_become_user  | default('root')}}"
conda_url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-{{core_arch}}.sh"
allow_world_readable_tmpfiles: true
conda_exec_path: "{{ core_conda_exec_path if core_conda_exec_path is defined else '' }}"
eval_path: "freva/evaluation_system.conf"
conda_cmd: "install"
base_path: ""
old_compose_dir: ""
data_dir: ""
service: ""
conda_pkgs:
    - python'>={{ core_python_version }}'
    - appdirs
    - curl
    - conda
    - gitpython
    - dask-core
    - django
    - humanize
    - ffmpeg
    - git
    - h5netcdf
    - lazy_import
    - metadata-inspector
    - mamba
    - micromamba
    - mysqlclient
    - netcdf4
    - numpy
    - pymysql
    - pandas
    - pillow
    - pypdf2'!=2.10.1'
    - requests
    - rich
    - setuptools
    - toml
    - toolz
    - typing_extensions
    - xarray
