---
- name: Include role vars
  include_vars: "{{ role_path }}/files/vars.yml"

- name: Set deployment task file
  set_fact:
    deployment_file: "{{ role_path }}/tasks/{{('k8s-deployment.yml' if deployment_method == 'k8s' else 'systemd-based.yml')}}"

- name: Run deployment - {{ deployment_file }}
  include_tasks: "{{ deployment_file | trim }}"
