---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Deleting containers
  shell: "{{ docker_bin }} {{ item }} || true"
  loop:
    - "stop {{ search_server_name }}"
    - "rm -f {{ search_server_name }}"
    - "rmi -f ghcr.io/freva-clint/freva-{{ search_server_service }}"
  changed_when: true

- name: Creating volumes
  include_tasks: "container-volumes.yml"

- name: Creating compose file
  template:
    src: "{{ search_server_service }}-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{search_server_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ search_server_name }} compose --enable --project-name {{ search_server_name }}
    -f {{ compose_file }} up --remove-orphans
  environment:
    PREFER: "{{ deployment_method }}"

- name: Wait for Solr to be available
  uri:
    url: "http://localhost:8983/solr/latest/admin/ping"
    status_code: 200
    timeout: 5
  register: result
  retries: 30
  delay: 5
  until: result.status == 200
  when: search_server_service == 'solr'

- name: Container healthchecks
  shell: >
    {{ docker_bin }} exec {{ search_server_name }} healthchecks
    -s {{ search_server_service }}
