---
- name: Deleting container
  shell: |
    {{ deployment_method }} stop {{ search_server_name }} || true
    {{ deployment_method }} rm -f {{ search_server_name }} || true
    {{deployment_method}} rmi -f ghcr.io/freva-clint/freva-{{ search_server_service }} || true
  changed_when: true

- name: Creating compose file
  template:
    src: "{{ search_server_service }}-compose.j2"
    dest: "{{ compose_file }}"

- name: Creating {{search_server_name}} service
  script: >
    {{ asset_dir }}/scripts/create_systemd.py
    {{ search_server_name }} compose --enable --project-name {{ search_server_name }}
    -f {{ compose_file }} up --remove-orphans
  environment:
    DEBUG: '{{ debug }}'
    PREFER: "{{ deployment_method }}"

- pause: seconds=30

- name: Container healthchecks
  script: >
    {{ docker_bin }} exec {{ search_server_name }} healthchecks
    -s {{ search_server_service }}
