---
- name: Running common taks
  include_tasks: "common_tasks.yml"

- name: Stopping the services
  systemd:
    name: "{{search_server_name}}"
    state: stopped
    enabled: false
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
  ignore_errors: true
  failed_when: false

- name: Removing old services files
  file:
    state: absent
    force: true
    path: "{{ systemd_unit_dir }}/{{ search_server_name }}.service"

- name: Playing the {{ deployment_method }} tasks
  include_tasks:
    file: "{{ deployment_file | trim }}"
