---
- name: Registering conda path
  stat:
    path: "{{ conda_path }}"
  register: conda_env_path

- name: Settting up conda and installing packages
  block:
    - name: Creating temporary directory
      tempfile:
        prefix: conda.
        state: directory
      register: conda_tempdir

    - name: Downloading miniforge
      script:
        cmd: "{{ asset_dir }}/scripts/download_conda.py {{ conda_tempdir.path }}"

    - name: Creating conda dir
      file:
        path: "{{ conda_path }}"
        recurse: true

    - name: Setting up conda environment
      shell:
        cmd: "./conda.sh -b -u -f -p {{ conda_path }}"
        chdir: "{{ conda_tempdir.path }}"

  always:

    - name: Removing temporary directory
      file:
        path: "{{ conda_tempdir.path }}"
        state: absent

  when: not conda_env_path.stat.exists

- name: Installing mamba packages {{conda_packages | join(' ')}}
  shell:
    cmd: >
      {{ conda_path }}/bin/mamba install -c conda-forge --override-channels
      -y {{ conda_packages | join(' ')}}
