---
- name: Set admin user variable
  set_fact:
    admin_user: >
        {{ admin_user
          if (admin_user | length > 0 and ansible_become | default(false) and ansible_become_user | default('root') == 'root')
          else ansible_user
        }}

- name: Get UID
  command: id -u {{ admin_user }}
  register: uid_result

- name: Get GID
  command: id -g {{ admin_user }}
  register: gid_result

- name: Set UID and GID as facts
  set_fact:
    uid: "{{ uid_result.stdout }}"
    gid: "{{ gid_result.stdout }}"

- name: Ensure the user systemd directory exists
  file:
    path: "{{ systemd_unit_dir }}"
    state: directory
    mode: "0755"
  when: systemd_unit_dir is defined

- name: Removing old compose directory structure
  file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "{{ old_compose_dir }}"
    - '{{ base_path }}/freva-service-config'
  when: base_path is defined and old_compose_dir is defined

- name: Registering systemctl path
  stat:
    path: /usr/bin/systemctl
  register: systemctl

- name: Registering anacron path
  stat:
    path: /etc/cron.daily
  register: cron

- include_tasks:
    file: "{{ general_tasks }}/service-config.yml"
  when: data_dir is defined

- name: Migrating volume directories
  script: >
    {{ asset_dir }}/scripts/migrate-volumes.sh
    --engine {{ deployment_method }}
    --old-parent-dir {{ base_path }}
    --project-name {{ project_name }}
