---
- name: Creating {{ data_dir }}
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    recurse: true

- name: Removing old service-config directory
  file:
    state: absent
    path: "{{ data_dir }}/freva-service-config"
