---
- hosts: dbservers

  vars:
    - ansible_python_interpreter: "{{ db_ansible_python_interpreter }}"
    - docker_cmd: "--net {{ project_name }} --name {{ db_name }} -e MYSQL_ROOT_PASSWORD='{{ root_passwd }}' -p {{ db_port }}:3306 mariadb:latest"
    - continer_name: "{{ db_name }}"
  tasks:
  - name: Registering systemctl path
    stat:
      path: /usr/bin/systemctl
    register: systemctl
  - name: Stopping services
    shell: docker stop {{db_name}}; docker rm {{db_name}}; systemctl stop {{ project_name }}; systemctl stop {{project_name}}-db; echo 0
    become: yes
    ignore_errors: yes
  - name: Creating docker network
    shell: docker network create "{{ project_name }}"; echo 0
    become: yes
  - name: Deleting existing contianer
    shell: docker stop "{{ db_name }}"; docker rm "{{ db_name }}"; echo 0
    become: yes
  - name: Installing mariadb docker image
    shell: docker pull mariadb
    become: yes
  - name: Copy systemd files
    copy:
      src: "{{ root_dir }}/{{ item }}"
      dest: /tmp/{{ item }}
      mode: '0755'
    with_items:
      - "systemd.service"
      - "create_systemd.sh"
  - name: Copy docker kill script
    copy:
      src: "{{ root_dir }}/kill_container"
      dest: /usr/local/bin/kill_container
      mode: '0755'
    become: yes
  - name: Running docker container
    become: yes
    shell: docker run -d {{docker_cmd}}
  - name: Preparing root password reset
    shell: echo "USE mysql; FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY '{{root_passwd}}'; ALTER USER 'root'@'%' IDENTIFIED BY '{{root_passwd}}'; FLUSH PRIVILEGES;" > /tmp/dump.sql
  - name: Copy sql script into docker container
    shell: docker cp /tmp/dump.sql {{db_name}}:/tmp/dump.sql
    become: yes
  - pause: seconds=5
  - name: Resetting the password
    shell: docker exec -it {{db_name}} /bin/bash -c "mysql -u root -p'{{ root_passwd }}' < /tmp/dump.sql"
    become: yes
    ignore_errors: yes
  - name: Deleting existing contianer
    shell: docker stop "{{ db_name }}"; docker rm "{{ db_name }}"; echo 0
    become: yes
  - name: Creating the mariadb docker container
    become: yes
    shell: docker run -d {{docker_cmd}}
  - name: Creating systemd service
    become: yes
    shell: "cat /tmp/systemd.service|sed 's#%STARTCMD#{{docker_cmd}}#g' |sed 's#%CONTAINER#{{ continer_name }}#g'|sed 's#%PROJECT#{{ project_name }}#g' > /tmp/tmp_db && mv /tmp/tmp_db /etc/systemd/system/{{ project_name }}-db.service && /tmp/create_systemd.sh {{project_name}}-db"
    when: systemctl.stat.exists == true
  - pause: seconds=5
  - name: Copying sample data to target machine
    # libselinux-python3 needs to be installed for this
    copy: src={{ db_dump }} dest=/tmp/dump.sql
  - name: Adding sql data to docker container
    shell: docker cp /tmp/dump.sql {{db_name}}:/tmp/dump.sql
    become: yes
  - name: Inserting sample data into database
    shell: docker exec -it {{db_name}} /bin/bash -c "mysql -u root -p'{{ root_passwd }}'< /tmp/dump.sql"
    become: yes
  - name: Deleting sql dump file
    file:
      state: absent
      path: "{{ item }}"
    with_items:
      - /tmp/dump.sql
      - /tmp/systemd.service
      - /tmp/create_systemd.sh
