---
service: freva_rest
ansible_become: "{{ freva_rest_ansible_become_user is defined and freva_rest_ansible_become_user != '' }}"
ansible_become_user: "{{ freva_rest_ansible_become_user | default('root') }}"
ansible_python_interpreter: "{{ freva_rest_ansible_python_interpreter }}"
admin_user: "{{ freva_rest_admin_user | default('') }}"
base_path: '{{freva_rest_data_path| regex_replace("^~", ansible_env.HOME)}}'
conda_path: '{{ base_path }}/{{ project_name }}/services/{{ service }}/conda'
systemd_unit_dir: "{{ '/etc/systemd/system' if  freva_rest_ansible_become_user is defined and freva_rest_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
freva_rest_name: "{{ project_name }}-freva_rest"
compose_file: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/compose_services/{{freva_rest_name}}-compose.yml'
old_compose_dir: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/compose_services'
data_dir: '{{freva_rest_data_path|regex_replace("^~", ansible_env.HOME)}}/{{ project_name }}/services/{{service}}'
conda_packages:
  - freva-rest-server
volume_names:
  - "{{ freva_rest_name }}_logs"

keycloak_dir: "{{ data_dir }}/keycloak"
keycloak_version: "26.2.5"
keycloak_url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.tar.gz"
keycloak_realm_import_url: "https://raw.githubusercontent.com/FREVA-CLINT/freva-service-config/refs/heads/main/keycloak/import/realm-export.json"
keycloak_realm_file_path: "{{ keycloak_dir }}/data/import/realm-export.json"
