---
- name: Running common conda tasks
  include_tasks: "{{ general_tasks }}/conda.yml"

- name: Creating service data directory structure in {{ volume_dir }}
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"
  with_items:
    - '{{ log_path }}/freva-rest-server'
    - "{{ cert_path }}"

- name: Writing ssl cert to file
  copy:
    content: "{{ cache_information.ssl_cert }}"
    dest: "{{ volume_dir }}/certs/client-cert.pem"
  when: cache_information.ssl_cert | length > 0

- name: Writing ssl key to file
  copy:
    content: "{{ cache_information.ssl_key }}"
    dest: "{{ volume_dir }}/certs/client-key.pem"
  when: cache_information.ssl_cert | length > 0

- name: Creating systemd unit service
  template:
    src: "systemd-conda.j2"
    dest: "{{ systemd_unit_dir }}/{{ freva_rest_name }}.service"
    mode: "0644"

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- name: Enable and start the {{ freva_rest_name }} service
  systemd:
    name: "{{ freva_rest_name }}"
    state: started
    enabled: true
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
