---
service: db
ansible_become: "{{ db_ansible_become_user is defined and db_ansible_become_user != '' }}"
ansible_python_interpreter: "{{ db_ansible_python_interpreter }}"
ansible_become_user: "{{ db_ansible_become_user | default('root') }}"
admin_user: "{{ db_admin_user | default('') }}"
base_path: '{{db_data_path| regex_replace("^~", ansible_env.HOME)}}'
conda_path: '{{ base_path }}/{{ project_name }}/conda'
systemd_unit_dir: "{{ '/etc/systemd/system' if  db_ansible_become_user is defined and db_ansible_become_user != '' else ansible_env.HOME + '/.config/systemd/user' }}"
compose_file: '{{db_data_path|regex_replace("^~", ansible_env.HOME)}}/{{project_name}}/compose_services/{{db_name}}-compose.yml'
old_compose_dir: '{{db_data_path|regex_replace("^~", ansible_env.HOME)}}/compose_services'
data_dir: '{{ base_path }}/{{project_name}}/services/{{service}}'
wipe: "{{ db_wipe }}"
upgrade_info_text: ""

volume_names:
  - "{{ db_name }}_data"
  - "{{ db_name }}_backup"
  - "{{ db_name }}_logs"

conda_packages:
  - 'mysql-server={{ db_version }}'
  - 'mysql-client={{ db_version }}'
