name: Creating the vault image

# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  contents: write
  packages: write

on:
  pull_request:
    types: [closed]
    branches:
      - main


jobs:
  build-and-push-vault-image:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      -
        name: Install packages
        run: |
         python3 -m pip install -e .

      -
        name: Get tag
        id: repository
        run: |
          echo "tag=$(python -c 'from freva_deployment import __version__;print(__version__)')" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push vault image
        uses: docker/build-push-action@v4
        with:
          context: assets/share/freva/deployment/vault/
          platforms: linux/amd64
          push: true
          build-args: VERSION=${{steps.repository.outputs.tag}}
          tags: |
            ghcr.io/freva-clint/freva-vault:${{ steps.repository.outputs.tag }}
            ghcr.io/freva-clint/freva-vault:latest
