name: Build the binary
run-name: ${{ github.actor }} building the pyinstaller binary 🧉

# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  contents: write
  packages: write

on:
  push:

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: linux-x86_64
            ASSET_MIME: application/octet-stream
            EXTRA_ARG: ""
          - os: macos-latest
            TARGET: macos-arm64
            ASSET_MIME: application/octet-stream
            EXTRA_ARG: --target-architecture arm64
          - os: macos-latest
            TARGET: macos-arm64
            ASSET_MIME: application/octet-stream
            EXTRA_ARG: --target-architecture arm64
          - os: windows-latest
            TARGET: windows
            ASSET_MIME: application/vnd.microsoft.portable-executable
            EXTRA_ARG: ""
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller ansible .
      - name: Build with cmd pyinstaller for ${{matrix.TARGET}}
        run: >
          pyinstaller pyinstaller/pyinstaller-deploy-freva.py
          -c --name deploy-freva --onefile --clean -i docs/_static/freva_owl.ico
          --add-data 'assets/share/freva/deployment:freva_deployment/assets'
          --add-data 'src/freva_deployment/versions.json:freva_deployment'
          ${{matrix.EXTRA_ARG}}
      - name: Upload cmd Asset
        id: upload-release-asset
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ASSET_TOKEN }}
        with:
          path: ./dist/deploy-freva-${{matrix.TARGET}}
          name: deploy-freva-${{ matrix.TARGET }}
          content_type: ${{ matrix.ASSET_MIME}}
