name: Bump version
run-name: ${{ github.actor }} is updating service versions 🧉


# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  contents: write
  packages: write

on:
  pull_request:
jobs:
  tests:
    uses: ./.github/workflows/ci_job.yml
  dependabot:
    name: Merge PR by dependabot
    runs-on: ubuntu-latest
    needs: tests
    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.TOKEN }}"
      - name: Approve dependabot's PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Auto-merge for dependabot's PR
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
  merge-pr:
    name: Merge PR
    runs-on: [ubuntu-latest]
    needs: tests
    if: github.event.pull_request.body == 'auto-bump'
    steps:
      - name: Auto-merge the PR
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
  tag:
    name: Create a new tag
    runs-on: [ubuntu-latest]
    needs: merge-pr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      - name: Install dependencies
        run: python3 -m pip install git-python packaging tomli requests
      - name: Create tag
        run: python3 release.py tag freva_deployment -b versions
        env:
          GIT_USER: ${{github.actor}}
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
