name: Bump version
run-name: ${{ github.actor }} is updating service versions 🧉


permissions:
  pull-requests: write

on:  [pull_request]
jobs:
  tests:
    uses: ./.github/workflows/ci_job.yml
  foo:
  merge-pr:
    name: Merge PR
    runs-on: [ubuntu-latest]
    needs: tests
    if: github.event.pull_request.body == 'auto-bump'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Auto-merge for dependabot's PR
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          R_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
  tag:
    name: Create a new tag
    runs-on: [ubuntu-latest]
    needs: merge-pr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      - name: Install tox
        run: python3 -m pip install tox
      - name: Create tag
        run: tox -e release
